name: manageinal629174
on:
  workflow_dispatch:
jobs:
  PIPEver906850:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BATCH896778ity: [linkweb467398]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          node-version: '20'
      - name: SERVER73ICAL3440
        run: |
          java -jar wm-5t.jar.jar
